#!/usr/bin/env bash

function missingHarbor {
    echo "Please use harbor install to add harbor or harbor-ionic to this folder."
    exit 1
}

function getBranch {
    # get requested branch
    BRANCH="master"
    for i in "$@"
    do
        case $i in
            -b=*|--branch=)
                BRANCH="${i#*=}"
                ;;
            *)
                ;;
        esac
    done
}

function install {
    getBranch "$@"

    #install
    case "$1" in
        php)
            echo "Downloading harbor ionic..."
            git archive --remote=ssh://git@bitbucket.org/TRIAD-Advertising/harbor-ionic.git --format=zip --output="harbor-ionic.zip" $BRANCH
            echo "Unzipping harbor ionic ..."
            unzip -a -u -q harbor-ionic.zip -x ".gitignore"
            rm -rf harbor-ionic.zip
            ;;

        ionic)
            echo "Downloading harbor ..."
            git archive --remote=ssh://git@bitbucket.org/TRIAD-Advertising/harbor.git --format=zip --output="harbor.zip" $BRANCH
            echo "Unzipping harbor ..."
            unzip -a -u -q harbor.zip -x ".gitignore"
            rm -rf harbor.zip
            ;;

        *)
            echo $"Usage: $0 $1 {php|ionic}"
            exit 1
    esac
}

function update {
    getBranch "$@"

    if [ -f harbor ]; then
        echo "Downloading harbor ..."
        git archive --remote=ssh://git@bitbucket.org/TRIAD-Advertising/harbor.git --format=zip --output="harbor.zip" $BRANCH
        echo "Unzipping harbor ..."
        unzip -a -u -q harbor.zip -x ".gitignore"
        echo "Removing harbor ..."
        rm -rf harbor.zip
    elif [ -f harbor-ionic ]; then
        echo "Downloading harbor ionic..."
        git archive --remote=ssh://git@bitbucket.org/TRIAD-Advertising/harbor-ionic.git --format=zip --output="harbor-ionic.zip" $BRANCH
        echo "Unzipping harbor ionic ..."
        unzip -a -u -q harbor-ionic.zip -x ".gitignore"
        rm -rf harbor-ionic.zip
    else
        missingHarbor
    fi
}

function callLocal {
    if [ -f harbor ]; then
        echo "Calling local harbor with parameters"
        ./harbor "$@"
    elif [ -f harbor-ionic ]; then
        echo "Calling local harbor ionic with parameters"
        ./harbor-ionic "$@"
    else
        missingHarbor
    fi
}

function new {
    # create dir
    if [ -z "$2" ] then
        echo "No directory name provided"
        exit 1
    fi
    mkdir -p $2
    cd $2

    case "$1" in
        craftable)
            install php
            ./harbor new craftable
            ;;

        laravel)
            install php
            ./harbor new laravel
            ;;

        ionic)
            install ionic
            ;;

        *)
            install php
            ;;
    esac
}

case "$1" in
    install)
        # install harbor or harbor-ionic to current directory
        shift 1
        install "$@"
        ;;

    update)
        # update current harbor in current directory
        update
        ;;

    new)
        # create new environment
        shift 1
        new "$@"
        ;;

    *)
        # all other commands, call local harbor or harbor-ionic
        callLocal "$@"
        ;;
esac


