#!/usr/bin/env bash

GITHUB_VENDOR_URL=https://github.com/BRACKETS-by-TRIAD/
HARBOR_LARAVEL=harbor-laravel
HARBOR_IONIC=harbor-ionic

function missingHarbor {
    echo "Please use harbor install to add harbor to this folder."
    exit 1
}

function getBranch {
    # get requested branch
    BRANCH="master"
    for i in "$@"
    do
        case ${i} in
            -b=*|--branch=*)
                BRANCH="${i#*=}"
                ;;
            *)
                ;;
        esac
    done
}

function getArgsForNew {
    BRANCH="master"
    DEV=""
    num=1
    for i in "$@"
    do
        case ${i} in
            -b=*|--branch=*)
                BRANCH="${i#*=}"
                ;;
            --dev)
                DEV="--dev"
                ;;

            *)
                if [ $num = 1 ]; then
                    TYPE=$i
                    num=$((num + 1))

                elif [ $num = 2 ]; then
                    DIR=$i
                    num=$((num + 1))

                fi
                ;;
        esac
    done
}

function getArgsForInstall {
    BRANCH="master"
    num=1
    for i in "$@"
    do
        case ${i} in
            -b=*|--branch=*)
                BRANCH="${i#*=}"
                ;;

            *)
                if [[ $num = 1 ]]; then
                    TYPE=$i
                    num=$((num + 1))
                fi
                ;;
        esac
    done
}

function install {
    getArgsForInstall "$@"

    case "$TYPE" in
        craftable|laravel|php)
            HARBOR=${HARBOR_LARAVEL}
            ;;

        ionic)
            HARBOR=${HARBOR_IONIC}
            ;;

        *)
            echo $"Usage: $0 install {craftable|laravel|php|ionic}"
            exit 1
    esac

    echo "Downloading harbor ..."
    curl -L ${GITHUB_VENDOR_URL}${HARBOR}/archive/${BRANCH}.zip > harbor.zip

    echo "Unzipping harbor ..."
    unzip -a -u -q harbor.zip
    HARBOR_DIR=${HARBOR}-${BRANCH}
    mv ${HARBOR_DIR}/README.md ./harbor-README.md
    rm -rf ${HARBOR_DIR}/.gitignore
    mv ${HARBOR_DIR}/* .

    echo "Removing zip file ..."
    rm -rf ${HARBOR_DIR}
    rm -rf harbor.zip
}

function update {
    getBranch "$@"

    if [[ -f harbor ]]; then
        TYPE=$(./harbor -t)

        case "$TYPE" in
            craftable|laravel|php)
                HARBOR=${HARBOR_LARAVEL}
                ;;

            ionic)
                HARBOR=${HARBOR_IONIC}
                ;;

            *)
                echo $"Usage: $0 update {craftable|laravel|php|ionic}"
                exit 1
        esac

        echo -n "Are you sure you want to update harbor, all customization in harbor files will be deleted (y/n)? "
        old_stty_cfg=$(stty -g)
        stty raw -echo ; answer=$(head -c 1) ; stty ${old_stty_cfg} # Careful playing with stty
        if echo "$answer" | grep -iq "^y" ;then
            echo "Downloading harbor ..."
            curl -L ${GITHUB_VENDOR_URL}${HARBOR}/archive/${BRANCH}.zip > harbor.zip

            echo "Removing old harbor ..."
            mkdir -p ./harbor-backup/
            mv docker docker-compose.yml harbor harbor-README.md ./harbor-backup/

            echo "Unzipping harbor ..."
            unzip -a -u -q harbor.zip
            HARBOR_DIR=${HARBOR}-${BRANCH}
            mv ${HARBOR_DIR}/README.md ./harbor-README.md
            rm -rf ${HARBOR_DIR}/.gitignore
            mv ${HARBOR_DIR}/* .
            if [[ -d "./harbor-backup/docker/php/ssh" ]]; then
                cp ./harbor-backup/docker/php/ssh/* ./docker/php/ssh/ 2>/dev/null
            fi

            echo "Clean up ..."
            rm -rf ${HARBOR_DIR}
            rm -rf harbor.zip
            rm -rf harbor-backup
        else
            echo "Aborted"
        fi
    else
        missingHarbor
    fi
}

function new {
    getArgsForNew "$@"

    # create dir
    if [[ -z "$DIR" ]]; then
        echo "No directory name provided."
        exit 1
    fi

    mkdir -p ${DIR}
    cd ${DIR}

    case "$TYPE" in
        craftable)
            install craftable -b=${BRANCH}
            ./harbor new craftable ${DEV}
            ;;

        laravel)
            install laravel -b=${BRANCH}
            ./harbor new laravel
            ;;

        php)
            install php -b=${BRANCH}
            ;;

        ionic)
            install ionic -b=${BRANCH}
            ./harbor new ionic
            ;;

        *)
            echo $"Usage: $0 new {craftable|laravel|php|ionic} /path/to/project"
            exit 1
            ;;
    esac
}

function callLocal {
    if [[ -f harbor ]]; then
        echo "Calling local harbor with parameters ..."
        ./harbor "$@"
    else
        missingHarbor
    fi
}

case "$1" in
    install)
        # install harbor to current directory
        shift 1
        install "$@"
        ;;

    update)
        # update harbor in current directory
        shift 1
        update "$@"
        ;;

    new)
        # create new environment
        shift 1
        new "$@"
        ;;

    *)
        # all other commands, call local harbor
        callLocal "$@"
        ;;
esac


