#!/usr/bin/env bash

function missingHarbor {
    echo "Please use harbor install to add harbor or harbor-ionic to this folder."
    exit 1
}

function getBranch {
    # get requested branch
    BRANCH="master"
    for i in "$@"
    do
        case $i in
            -b=*|--branch=)
                BRANCH="${i#*=}"
                ;;
            *)
                ;;
        esac
    done
}

function getArgsForNew {
    BRANCH="master"
    num=1
    for i in "$@"
    do
        case $i in
            -b=*|--branch=)
                BRANCH="${i#*=}"
                ;;

            *)
                if [ $num = 1 ]; then
                    TYPE=$i
                    num=$((num + 1))

                elif [ $num = 2 ]; then
                    DIR=$i
                    num=$((num + 1))

                fi
                ;;
        esac
    done
}

function getArgsForInstall {
    BRANCH="master"
    num=1
    for i in "$@"
    do
        case $i in
            -b=*|--branch=)
                BRANCH="${i#*=}"
                ;;

            *)
                if [ $num = 1 ]; then
                    TYPE=$i
                    num=$((num + 1))
                fi
                ;;
        esac
    done
}

function install {
    getArgsForInstall "$@"

    #install
    case "$TYPE" in
        php)
            echo "Downloading harbor ..."
            git archive --remote=ssh://git@bitbucket.org/TRIAD-Advertising/harbor.git --format=zip --output="harbor.zip" $BRANCH
            echo "Unzipping harbor ..."
            unzip -a -u -q harbor.zip -x ".gitignore"
            rm -rf harbor.zip
            ;;

        ionic)
            echo "Downloading harbor ionic..."
            git archive --remote=ssh://git@bitbucket.org/TRIAD-Advertising/harbor-ionic.git --format=zip --output="harbor-ionic.zip" $BRANCH
            echo "Unzipping harbor ionic ..."
            unzip -a -u -q harbor-ionic.zip -x ".gitignore"
            rm -rf harbor-ionic.zip
            ;;

        *)
            echo $"Usage: $0 install {php|ionic}"
            exit 1
    esac
}

function update {
    getBranch "$@"

    if [ -f harbor ]; then
        echo -n "Are you sure you want to update harbor, all customization in harbor files will be deleted (y/n)? "
        old_stty_cfg=$(stty -g)
        stty raw -echo ; answer=$(head -c 1) ; stty $old_stty_cfg # Careful playing with stty
        if echo "$answer" | grep -iq "^y" ;then
            echo "Downloading harbor ..."
            git archive --remote=ssh://git@bitbucket.org/TRIAD-Advertising/harbor.git --format=zip --output="harbor.zip" $BRANCH

            echo "Removing old harbor ..."
            mkdir -p ./harbor-backup/
            mv docker docker-compose.yml harbor harbor-readme.md ./harbor-backup/

            echo "Unzipping harbor ..."
            unzip -a -u -q harbor.zip -x ".gitignore"
            cp ./harbor-backup/docker/php/ssh/* ./docker/php/ssh/

            echo "Clean up ..."
            rm -rf harbor.zip
            rm -rf harbor-backup
        else
            echo "Aborted"
        fi

    elif [ -f harbor-ionic ]; then
        echo -n "Are you sure you want to update harbor, all customization in harbor files will be deleted (y/n)? "
        old_stty_cfg=$(stty -g)
        stty raw -echo ; answer=$(head -c 1) ; stty $old_stty_cfg # Careful playing with stty
        if echo "$answer" | grep -iq "^y" ;then
            echo "Downloading harbor ionic..."
            git archive --remote=ssh://git@bitbucket.org/TRIAD-Advertising/harbor-ionic.git --format=zip --output="harbor-ionic.zip" $BRANCH

            echo "Removing old harbor ionic ..."
            rm -rf docker docker-compose.yml harbor-ionic harbor-ionic-readme.md

            echo "Unzipping harbor ionic ..."
            unzip -a -u -q harbor-ionic.zip -x ".gitignore"

            echo "Clean up ..."
            rm -rf harbor-ionic.zip
        else
            echo "Aborted"
        fi
    else
        missingHarbor
    fi
}

function callLocal {
    if [ -f harbor ]; then
        echo "Calling local harbor with parameters"
        ./harbor "$@"
    elif [ -f harbor-ionic ]; then
        echo "Calling local harbor ionic with parameters"
        ./harbor-ionic "$@"
    else
        missingHarbor
    fi
}

function new {
    getArgsForNew "$@"

    # create dir
    if [ -z "$DIR" ]; then
        echo "No directory name provided"
        exit 1
    fi

    mkdir -p $DIR
    cd $DIR

    case "$TYPE" in
        craftable)
            install php -b=$BRANCH
            ./harbor new craftable
            ;;

        laravel)
            install php -b=$BRANCH
            ./harbor new laravel
            ;;

        ionic)
            install ionic -b=$BRANCH
            ./harbor-ionic new ionic
            ;;

        empty)
            install php -b=$BRANCH
            ;;

        *)
            install php -b=$BRANCH
            ;;
    esac
}

case "$1" in
    install)
        # install harbor or harbor-ionic to current directory
        shift 1
        install "$@"
        ;;

    update)
        # update current harbor in current directory
        shift 1
        update "$@"
        ;;

    new)
        # create new environment
        shift 1
        new "$@"
        ;;

    *)
        # all other commands, call local harbor or harbor-ionic
        callLocal "$@"
        ;;
esac


